### ISSUE TITLE
Theme Asset Files Not Included

### ISSUE THREAD

**Issue by srsgores** [IvyApp/ivy-codemirror#1]
It appears that upon installation, only the ``default`` theme can be used, as other codeMirror themes are not bundled, using the ``ember g ivy-codemirror`` command.

Would be nice to see a fixl.

**Comment by jsalva** [comment]
yea having the same issue; I got my theme working by including the theme explicitly in the brocfile.js
```javascript
app.import('bower_components/codemirror/theme/paraiso-dark.css');
```

However, modes don't work as they're also not imported. I tried doing the same thing for the `bower_components/codemirror/mode/htmlmixed/htmlmixed.js` but I'm getting an error 
```javascript
var state = htmlMode.startState(); // Uncaught TypeError: undefined is not a function, line 89
```

**Comment by omghax** [comment]
Thanks for the issue. I added this feature a while back but forgot to document it in the README. I've updated it here: https://github.com/IvyApp/ivy-codemirror#themes--modes. You can also look at the project's `Brocfile.js` for an example of including all modes and themes (this is the "dummy" app that runs on GitHub pages): https://github.com/IvyApp/ivy-codemirror/blob/master/Brocfile.js#L7-L34.

@jsalva Hmm, I've never tried using the htmlmixed mode. According to http://codemirror.net/mode/htmlmixed/, HTML mixed mode requires the XML, Javascript, and CSS modes. Did you include all of those as well?

**Comment by jsalva** [comment]
worked; amazing, and thanks for making this component. Many props

**Comment by srsgores** [comment]
@omghax, can you clarify on how this would work in ember-cli?

I tried as you suggest, and I get nothing:

```
 App = Ember.Application.extend({
    codemirror: {
      modes: ["javascript", "markdown", "css"],
      themes: ["ambiance"]
    },
    modulePrefix: config.modulePrefix,
    podModulePrefix: config.podModulePrefix,
    Resolver: Resolver
  });
```
