### ISSUE TITLE
PR for binding to any arbitrary action?

### ISSUE THREAD

**Issue by drapergeek** [IvyApp/ivy-codemirror#13]
Hello all!

I'd love to submit a PR that will allow the user to listen for any event on the component and accept it as an action.

Something like this:
```handlebars
{{ivy-code value=value blur=(action "editorBlurred")}
```

Is that something you all are interested in? I'll start on a PR if so, wasn't going to bother with a PR if you all don't care to add the functionality.

**Comment by Iftahh** [comment]
I'm interested!
