### ISSUE TITLE
Problem with bootstrap modal dialog

### ISSUE THREAD

**Issue by igorstajic** [IvyApp/ivy-codemirror#2]
I have a codemirror component inside bootstrap modal, and when the modal dialog is shown i need to click on the editor in order for it to display contents. I know this issue is related to modal part being hidden on page render, but I was wondering is there an easy fix for this, since I'm new with using ember cli.

**Comment by omghax** [comment]
There's an `isVisible` property you can set on the `ivy-codemirror` component that will cause CodeMirror to refresh when it becomes `true`. I'm not sure about the particulars of your Bootstrap modal, but if you bind `isVisible` to some property that indicates when the modal is shown, everything should work.

For example:

```handlebars
{{ivy-codemirror isVisible=isModalVisible}}
```

**Comment by igorstajic** [comment]
Tnx for the response. Don't know how I didn't notice that property...

**Comment by omghax** [comment]
No worries, it's easy to miss. It's actually something that all `Ember.View` classes support, along with `becameVisible` and `becameHidden` hooks.

Take a look [here](https://github.com/emberjs/ember.js/blob/v1.11.1/packages/ember-views/lib/mixins/visibility_support.js#L11-L18) if you're curious.
