### ISSUE TITLE
avoid relying upon bower to import code mirror dependencies

### ISSUE THREAD

**Issue by efx** [IvyApp/ivy-codemirror#26]
This isn't a blocker or anything but just wanted to note that ember-cli@2.13 no longer installs bower by default for ember applications. It would be best to import the codemirror dependencies through npm and perhaps fallback to bower.

**Comment by omghax** [comment]
Just released 2.1.0, which gets rid of Bower 🎉

**Comment by efx** [comment]
excellent, thanks @omghax !
