### ISSUE TITLE
Custom mode

### ISSUE THREAD

**Issue by pradius-fut** [IvyApp/ivy-codemirror#3]
Hi,
is it possible to use a custom mode with this component?
I'm converting a project from Backbone/requirejs to Ember/ember-cli and would like to use my own mustache mode.

**Comment by omghax** [comment]
Yeah, you'd just need to import it in your app's `Brocfile.js`, like so:

```javascript
app.import('path/to/custom_mustache.js');
```

Then reference it like you would with any of the built-in modes:

```handlebars
{{ivy-codemirror mode="custom_mustache"}}
```

Take a look at the [Ember CLI docs](http://www.ember-cli.com/#javascript-assets) for more info about importing js files.
